### ISSUE TITLE
Error opening this project

### ISSUE THREAD

**Issue by adetheprince** [tirgei/MpesaDaraja#1]
Desktop\Android Projects\MpesaDaraja-master\app\src\main\java\com\gelostech\mpesadaraja\activities\MainActivity.kt: (75, 30): Unresolved reference: Constants

**Comment by tirgei** [comment]
> Desktop\Android Projects\MpesaDaraja-master\app\src\main\java\com\gelostech\mpesadaraja\activities\MainActivity.kt: (75, 30): Unresolved reference: Constants

What's the issue exactly?

**Comment by adetheprince** [comment]
looks like that file is missing? Constants.

import com.gelostech.mpesadaraja.commoners.Constants.
I know it may contain keys and personal data but would it be possible to see the sample?

**Comment by tirgei** [comment]
Yeah.. it's supposed to contain these:

```
object Constants {

    const val PAYBILL = ""
    const val CONSUMER_KEY = ""
    const val CONSUMER_SECRET = ""
    const val CALLBACK_URL = ""
    const val PASSKEY = ""
    const val ACCOUNT_REF = ""
    const val UPDATE_BALANCE_URL = ""

}
```

You can get them from your Safaricom Portal & the callbacks/update balance from deployment of [M-Pesa Daraja Functions](https://github.com/tirgei/mpesa-daraja-functions)
